FROM mcr.microsoft.com/devcontainers/typescript-node:20-bookworm

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get upgrade -y

# RUN apt-get install gjs
# RUN apt-get install libgtk-3-dev
# RUN apt-get install gh
